"""Added many-to-many relationship between Car and Garage

Revision ID: cb89a53c420b
Revises: d7bae891a53c
Create Date: 2024-12-30 19:10:17.610864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb89a53c420b'
down_revision: Union[str, None] = 'd7bae891a53c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargarage',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('garage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.ForeignKeyConstraint(['garage_id'], ['garage.id'], ),
    sa.PrimaryKeyConstraint('car_id', 'garage_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cargarage')
    # ### end Alembic commands ###
